---
otelcol_version: "0.154.0"
opampsupervisor_version: "{{ otelcol_version }}"

xscaler_opamp_endpoint: "wss://agents.xscalerlabs.com/v1/opamp"
xscaler_agent_name: "{{ inventory_hostname }}"
xscaler_agent_labels: {}
